---

- name: Create work directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  loop:
  - "{{ conf_dir }}"
  - "{{ data_dir }}"
  - "{{ logs_dir }}"
  - "{{ run_dir }}"

- name: Generate config file
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_file }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: 0644
  notify: "Restart service"

- name: Create systemd service
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    mode: 0644

- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

- name: Ensure service is running
  systemd:
    name: "{{ systemd_service_name }}"
    state: started
  tags:
  - start
