---

- name: Check Ansible version
  fail:
    msg: >
      This role does not support Ansible version < 2.6.
  when:
    - ansible_version.full < 2.6

- name: Check OS type
  fail:
    msg: "This role only supports Redhat Linux!"
  when:
    - ansible_os_family != 'RedHat'

- name: Check master_group and replica_group
  fail:
    msg: >
      Error: you must specify the master group name or replica group name in cluster mode.
  when:
    - master_group == ''
    - replica_group == ''
    - redis_cluster_enabled == 'yes'

- name: Check replicaof directive
  fail:
    msg: >
      Error: replicaof directive not allowed in cluster mode
  when:
  - redis_cluster_enabled == 'yes'
  - redis_replicaof != false

